version: 2

models:
  - name: stg_customers
    description: "Tabela limpa de clientes do e-commerce."
    columns:
      - name: customer_id
        description: "Chave primária do cliente para um pedido específico."
        tests:
          - unique
          - not_null
      - name: customer_unique_id
        description: "Identificador único real do cliente."
        tests:
          - not_null

  - name: stg_orders
    description: "Tabela limpa de pedidos."
    columns:
      - name: order_id
        description: "Chave primária do pedido."
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Chave estrangeira mapeando para stg_customers."
        tests:
          - not_null
          # Teste de Integridade: O customer_id deste pedido DEVE existir na tabela de clientes
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: order_status
        description: "Status atual do pedido."
        tests:
          # Teste de Regra de Negócio: O status tem que ser obrigatoriamente um desses abaixo
          - accepted_values:
              values: 
                - created
                - approved
                - invoiced
                - processing
                - shipped
                - delivered
                - unavailable
                - canceled